---
version: '3.4'

services:
  ctn1:
    build:
      context: .
    logging:
      driver: journald
      options:
        tag: "ctn1"
        mode: "non-blocking"
        max-buffer-size: "5b"
        # mode: "blocking"
